# Generated by Django 3.2.9 on 2021-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_drop_off_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='drop_off_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
